import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';
const server=spawn(process.execPath,['node_modules/vite/bin/vite.js','preview','--config','browser-test.config.ts','--host','127.0.0.1','--port','4174'],{stdio:'ignore',windowsHide:true});
let browser;try{
 for(let i=0;i<50;i++){try{if((await fetch('http://127.0.0.1:4174/browser-test.html')).ok)break;}catch{}await new Promise(r=>setTimeout(r,200));}
 browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true,args:['--autoplay-policy=no-user-gesture-required','--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:1280,height:900}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const id='10000000-0000-4000-8000-000000000001',host='00000000-0000-4000-8000-000000000001',guest='00000000-0000-4000-8000-000000000002';
 let state={game:{id,host_id:host,title:'Department Championship',status:'scheduled',is_proctored:false,max_players:200,start_datetime:'2030-01-01T12:00:00Z'},phase:'lobby',players:[{user_id:host,full_name:'Host',connected:true,current_score:0,life_tokens:3,jackpot_balance:100},{user_id:guest,full_name:'Guest',connected:true,current_score:0,life_tokens:3,jackpot_balance:100}],question_count:15,lifelines:{used_fifty:false,used_peek:false,hidden_options:null,peek:null},wager:null,answer:null};
 const calls=[];await page.route('**/rest/v1/rpc/**',async route=>{const name=route.request().url().split('/').pop(),args=route.request().postDataJSON();calls.push({name,args});let response=null;if(name==='remote_room_state')response={...state,server_now:new Date().toISOString(),boundary:new Date(Date.now()+25000).toISOString()};await route.fulfill({json:response});});
 await page.goto('http://127.0.0.1:4174/browser-test.html');await page.getByRole('button',{name:'Start tournament now'}).waitFor();assert.equal(await page.getByRole('button',{name:'Start tournament now'}).isEnabled(),true);await page.getByRole('button',{name:'Start tournament now'}).click();assert.ok(calls.some(c=>c.name==='start_remote_game'));
 assert.ok(await page.getByText('Connected Room Participants (2)').isVisible());await page.evaluate(()=>window.setGuest());assert.equal(await page.getByRole('button',{name:'Start tournament now'}).count(),0);
 state={...state,game:{...state.game,status:'active'},phase:'answer',round:{round_number:2,section_key:'Chapter 12 Section 2',sections:['Chapter 12 Section 2']},question:{id:'q1',question_text:'You are asked to travel before leave approval.',options:['Seek authorization','Travel now','Hide absence','Use a colleague'],question_order:5,round_number:2,base_points:20,life_cost:0,correct_option_index:null}};
 await page.getByRole('button',{name:'50:50',exact:true}).waitFor({timeout:10000});await page.getByRole('button',{name:'50:50',exact:true}).click();assert.ok(calls.some(c=>c.name==='use_contest_lifeline'&&c.args.p_kind==='fifty'));
 await page.getByRole('button',{name:'Rulebook Peek',exact:true}).click();assert.ok(calls.some(c=>c.name==='use_contest_lifeline'&&c.args.p_kind==='peek'));
 state={...state,phase:'wager',round:{...state.round,round_number:3},question:{...state.question,round_number:3,question_order:10,life_cost:1,base_points:10}};await page.getByRole('button',{name:'50',exact:true}).waitFor({timeout:10000});await page.getByRole('button',{name:'50',exact:true}).click();assert.ok(calls.some(c=>c.name==='place_contest_wager'&&c.args.p_amount===50));
 // Use a static supplied portrait only as a local test camera fixture. All network writes are mocked.
 await page.evaluate(async()=>{const img=new Image();img.src=window.portrait;await img.decode();const canvas=document.createElement('canvas');canvas.width=640;canvas.height=480;const draw=()=>canvas.getContext('2d').drawImage(img,0,0,640,480);draw();setInterval(draw,100);Object.defineProperty(navigator.mediaDevices,'getUserMedia',{value:async()=>canvas.captureStream(10)});Object.defineProperty(navigator.mediaDevices,'getDisplayMedia',{value:async()=>{const stream=canvas.captureStream(10);const track=stream.getVideoTracks()[0],base=track.getSettings.bind(track);track.getSettings=()=>({...base(),displaySurface:'monitor'});return stream;}});window.renderProctor();});
 await page.getByRole('checkbox').check();await page.getByRole('button',{name:'1. Enable camera',exact:true}).click();await page.getByRole('button',{name:'2. Share entire screen',exact:true}).click();await page.getByRole('button',{name:'3. Enter fullscreen',exact:true}).click();
 try{await page.waitForFunction(()=>window.proctorReady===true,{},{timeout:45000});}catch(e){console.log('MONITOR_DIAGNOSTIC',await page.locator('body').innerText(),errors);throw e;}
 assert.ok(calls.some(c=>c.name==='proctor_heartbeat'&&c.args.p_ready===true&&c.args.p_camera?.startsWith('data:image/jpeg')));
 const exitEvent=page.waitForRequest(r=>r.url().endsWith('/proctor_event')&&r.postDataJSON()?.p_kind==='fullscreen_exit');await page.evaluate(()=>document.exitFullscreen());await exitEvent;await page.waitForFunction(()=>window.proctorReady===false);assert.ok(calls.some(c=>c.name==='proctor_event'&&c.args.p_kind==='fullscreen_exit'));
 await page.getByRole('button',{name:'Stop monitoring',exact:true}).click();assert.equal(await page.getByRole('checkbox').isChecked(),false);
 assert.deepEqual(errors,[]);console.log('PASS: host/guest controls, participant count, lifelines, jackpot UI, real face worker, consent, preview heartbeat, fullscreen interruption and stop cleanup. Media permissions were simulated, not real devices.');
}finally{await browser?.close();server.kill();}
