import React,{useEffect,useRef,useState} from 'react';
import {contestRpc} from '../../services/remoteContest';
interface Audit {total:number;participants:{user_id:string;full_name:string;ready:boolean;last_seen:string|null;camera:string|null;screen:string|null}[];events:{id:string;full_name:string;kind:string;created_at:string;reviewed_at:string|null;note:string|null}[]}
const btn='bg-slate-800 text-white rounded-lg px-4 py-2 text-sm font-bold disabled:opacity-40';
export function ProctorReview({gameId}:{gameId:string}){
 const [page,setPage]=useState(0),[data,setData]=useState<Audit|null>(null),[error,setError]=useState(''),[notes,setNotes]=useState<Record<string,string>>({});
 useEffect(()=>{let live=true,loading=false;const load=async()=>{if(loading)return;loading=true;try{const d=await contestRpc<Audit>('proctor_dashboard',{p_game_id:gameId,p_page:page});if(live){setData(d);setError('');}}catch(e){if(live)setError(String(e));}finally{loading=false;}};void load();const timer=setInterval(load,5000);return()=>{live=false;clearInterval(timer);};},[gameId,page]);
 return <section className="space-y-4"><h3 className="font-black">Host / administrator monitoring</h3><p className="text-xs text-slate-500">Camera and entire-screen previews refresh every 5 seconds. These are periodic snapshots, not continuous video recordings. Automated flags require human review.</p>{error&&<p role="alert" className="text-rose-700">{error}</p>}{!data?<p>Loading monitor…</p>:<><div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-3">{data.participants.map(p=><div key={p.user_id} className="border rounded-xl p-3 space-y-2"><strong>{p.full_name}</strong><p className={p.ready?'text-emerald-700 text-xs':'text-amber-700 text-xs'}>{p.ready?'Proctor setup ready':'Not ready / connection stale'}</p><div className="flex gap-2">{p.camera?<img className="w-1/3 object-contain bg-slate-950 rounded" src={p.camera} alt={`${p.full_name} camera preview`}/>:<span className="text-xs">No camera</span>}{p.screen?<a href={p.screen} target="_blank" rel="noreferrer" className="w-2/3"><img src={p.screen} alt={`${p.full_name} shared screen preview`} className="w-full rounded"/></a>:<span className="text-xs">No screen</span>}</div><p className="text-xs text-slate-500">{p.last_seen?new Date(p.last_seen).toLocaleTimeString():'Awaiting consent and setup'}</p></div>)}</div><div className="flex gap-3 items-center"><button className={btn} disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1} / {Math.max(1,Math.ceil(data.total/12))}</span><button className={btn} disabled={(page+1)*12>=data.total} onClick={()=>setPage(p=>p+1)}>Next</button></div><details><summary className="font-bold">Review flags ({data.events.length} most recent)</summary><div className="space-y-3 max-h-96 overflow-y-auto mt-3">{data.events.length===0?<p>No flags recorded.</p>:data.events.map(e=><div key={e.id} className="border rounded-xl p-3 text-sm"><strong>{e.full_name} · {e.kind.split('_').join(' ')}</strong><p>{new Date(e.created_at).toLocaleString()}</p>{e.reviewed_at?<p>Reviewed: {e.note}</p>:<div className="flex flex-wrap gap-2 mt-2"><input aria-label="Review note" value={notes[e.id]||''} maxLength={1000} onChange={v=>setNotes(n=>({...n,[e.id]:v.target.value}))} placeholder="Record the human review outcome" className="border rounded-lg p-2 grow"/><button className={btn} onClick={async()=>{try{await contestRpc('proctor_review',{p_event_id:e.id,p_note:notes[e.id]||''});setData(d=>d?{...d,events:d.events.map(x=>x.id===e.id?{...x,reviewed_at:new Date().toISOString(),note:notes[e.id]}:x)}:d);}catch(err){setError(String(err));}}}>Save review</button></div>}</div>)}</div></details></>}</section>;
}
export function ProctorPanel({gameId,host,active,onReady}:{gameId:string;host:boolean;active:boolean;onReady:(ready:boolean)=>void}){
 const [consent,setConsent]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('Complete the three setup steps'),[cameraOn,setCameraOn]=useState(false),[screenOn,setScreenOn]=useState(false),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[review,setReview]=useState(false);
 const camera=useRef<HTMLVideoElement>(null),screen=useRef<HTMLVideoElement>(null),camStream=useRef<MediaStream|null>(null),screenStream=useRef<MediaStream|null>(null),worker=useRef<Worker|null>(null),modelReady=useRef(false),processing=useRef(false),lastFace=useRef(0),faces=useRef(0),gazeSince=useRef(0),faceSince=useRef(0),lastFlag=useRef<Record<string,number>>({}),live=useRef(true),consented=useRef(false),heartbeatBusy=useRef(false);
 const setHealthy=(value:boolean)=>{if(live.current){setReady(value);onReady(value);}};
 const flag=(kind:string)=>{if(!consented.current||Date.now()-(lastFlag.current[kind]||0)<10000)return;lastFlag.current[kind]=Date.now();void contestRpc('proctor_event',{p_game_id:gameId,p_kind:kind}).catch(e=>{if(live.current)setError('Proctor connection: '+String(e));});};
 const stop=()=>{consented.current=false;camStream.current?.getTracks().forEach(t=>t.stop());screenStream.current?.getTracks().forEach(t=>t.stop());camStream.current=null;screenStream.current=null;worker.current?.terminate();worker.current=null;modelReady.current=false;processing.current=false;setHealthy(false);if(live.current){setCameraOn(false);setScreenOn(false);setConsent(false);}void contestRpc('proctor_stop',{p_game_id:gameId}).catch(()=>{});};
 useEffect(()=>{live.current=true;return()=>{live.current=false;stop();onReady(false);};},[gameId]);
 useEffect(()=>{if(!active)stop();},[active]);
 useEffect(()=>{
  if(!active)return;
  const visibility=()=>{if(document.hidden){setHealthy(false);flag('tab_hidden');}};
  const blur=()=>{setHealthy(false);flag('focus_lost');};
  const fullscreen=()=>{if(!document.fullscreenElement){setHealthy(false);flag('fullscreen_exit');}};
  document.addEventListener('visibilitychange',visibility);document.addEventListener('fullscreenchange',fullscreen);window.addEventListener('blur',blur);
  const capture=(video:HTMLVideoElement|null,width:number)=>{if(!video||video.readyState<2||!video.videoWidth)return null;const canvas=document.createElement('canvas');canvas.width=width;canvas.height=Math.round(width*video.videoHeight/video.videoWidth);const ctx=canvas.getContext('2d');if(!ctx)return null;ctx.drawImage(video,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',0.55);};
  const timer=setInterval(async()=>{
   if(!consented.current||!live.current)return;
   if(modelReady.current&&!processing.current&&camera.current&&camera.current.readyState>=2){processing.current=true;try{const frame=await createImageBitmap(camera.current,{resizeWidth:320});if(worker.current)worker.current.postMessage({type:'frame',frame,time:performance.now()},[frame]);else{frame.close();processing.current=false;}}catch{processing.current=false;setHealthy(false);flag('monitor_error');}}
   const cam=camStream.current?.getVideoTracks()[0],scr=screenStream.current?.getVideoTracks()[0];
   const healthy=!!document.fullscreenElement&&!document.hidden&&document.hasFocus()&&cam?.readyState==='live'&&!cam.muted&&scr?.readyState==='live'&&!scr.muted&&scr.getSettings().displaySurface==='monitor'&&modelReady.current&&Date.now()-lastFace.current<5000&&faces.current===1;
   if(!healthy){setHealthy(false);setStatus(!document.fullscreenElement?'Enter fullscreen to continue':!document.hasFocus()?'Return focus to the contest':!modelReady.current?'Loading face monitor…':faces.current!==1?'Keep one clearly visible face in the camera':'Restore camera and entire-screen sharing');}
   if(heartbeatBusy.current||Date.now()-(lastFlag.current.heartbeat||0)<4000)return;heartbeatBusy.current=true;lastFlag.current.heartbeat=Date.now();
   try{await contestRpc('proctor_heartbeat',{p_game_id:gameId,p_consent:true,p_ready:healthy,p_camera:capture(camera.current,240),p_screen:capture(screen.current,640)});if(live.current&&consented.current){setHealthy(healthy);if(healthy){setStatus('Proctoring active · camera, screen, fullscreen and face monitor ready');setError('');}}}catch(e){setHealthy(false);if(live.current)setError(String(e));}finally{heartbeatBusy.current=false;}
  },750);
  return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',visibility);document.removeEventListener('fullscreenchange',fullscreen);window.removeEventListener('blur',blur);};
 },[gameId,active]);
 const enableCamera=async()=>{setBusy(true);setError('');consented.current=true;try{
  if(!navigator.mediaDevices?.getUserMedia||!window.Worker)throw Error('This browser cannot run the required camera monitor. Use a supported desktop browser.');
  camStream.current?.getTracks().forEach(t=>t.stop());const stream=await navigator.mediaDevices.getUserMedia({video:{width:640,height:480},audio:false});if(!live.current){stream.getTracks().forEach(t=>t.stop());return;}camStream.current=stream;if(camera.current){camera.current.srcObject=stream;await camera.current.play();}setCameraOn(true);
  stream.getVideoTracks()[0].onended=()=>{setHealthy(false);setCameraOn(false);flag('camera_stopped');};
  worker.current?.terminate();worker.current=new Worker(new URL('../../workers/faceMonitor.ts',import.meta.url));modelReady.current=false;
  worker.current.onerror=()=>{modelReady.current=false;setHealthy(false);flag('monitor_error');setError('Face monitor could not start. Retry camera setup.');};
  worker.current.onmessage=e=>{if(!live.current)return;if(e.data.type==='ready'){modelReady.current=true;}else if(e.data.type==='error'){modelReady.current=false;processing.current=false;setHealthy(false);setError('Face monitor unavailable: '+e.data.message);flag('monitor_error');}else if(e.data.type==='result'){processing.current=false;faces.current=e.data.faces;lastFace.current=Date.now();if(e.data.faces!==1){faceSince.current||=Date.now();if(Date.now()-faceSince.current>3000)flag(e.data.faces>1?'multiple_faces':'face_missing');}else faceSince.current=0;if(e.data.gazeAway){gazeSince.current||=Date.now();if(Date.now()-gazeSince.current>3000)flag('gaze_away');}else gazeSince.current=0;}};
  worker.current.postMessage({type:'init',origin:location.origin});
 }catch(e){setError(String(e));setHealthy(false);}finally{if(live.current)setBusy(false);}};
 const enableScreen=async()=>{setError('');try{if(!navigator.mediaDevices?.getDisplayMedia)throw Error('Entire-screen sharing is unavailable in this browser. Use a supported desktop browser.');const stream=await navigator.mediaDevices.getDisplayMedia({video:{displaySurface:'monitor'},audio:false});if(stream.getVideoTracks()[0].getSettings().displaySurface!=='monitor'){stream.getTracks().forEach(t=>t.stop());throw Error('Select Entire screen, not a browser tab or window.');}if(!live.current){stream.getTracks().forEach(t=>t.stop());return;}screenStream.current?.getTracks().forEach(t=>t.stop());screenStream.current=stream;if(screen.current){screen.current.srcObject=stream;await screen.current.play();}setScreenOn(true);stream.getVideoTracks()[0].onended=()=>{setHealthy(false);setScreenOn(false);flag('screen_stopped');};}catch(e){setError(String(e));}};
 return <section className="bg-slate-50 border border-slate-200 rounded-3xl p-5 space-y-4"><h2 className="font-black text-lg">Proctored tournament</h2>{active&&<><p className="text-sm">Camera and whole-screen previews are visible to this tournament’s host and app administrators. Close private material before sharing. Face count and possible sustained gaze changes are analysed on your device; flags are for human review and are not proof of misconduct.</p><p className="text-xs text-slate-500">No audio is collected. Only the latest previews are stored; they are removed when you stop, or within 6 minutes of disconnection. Event logs are retained for 30 days. Fullscreen or sharing interruptions block new answers while the contest timer continues. This browser-based monitoring cannot detect every external device or application.</p><label className="flex gap-2 text-sm font-semibold"><input type="checkbox" checked={consent} disabled={cameraOn||screenOn} onChange={e=>{setConsent(e.target.checked);consented.current=e.target.checked;}}/>I agree to this monitoring for this tournament.</label><div className="flex flex-wrap gap-2"><button className={btn} disabled={!consent||busy} onClick={()=>void enableCamera()}>{busy?'Starting camera…':cameraOn?'Restart camera monitor':'1. Enable camera'}</button><button className={btn} disabled={!consent} onClick={()=>void enableScreen()}>{screenOn?'Replace screen share':'2. Share entire screen'}</button><button className={btn} disabled={!consent} onClick={()=>document.documentElement.requestFullscreen().catch(e=>setError(String(e)))}>3. Enter fullscreen</button><button className={btn} onClick={stop}>Stop monitoring</button></div><div className="flex gap-3"><video ref={camera} autoPlay muted playsInline className="w-32 rounded-lg bg-slate-900" aria-label="Your camera preview"/><video ref={screen} autoPlay muted playsInline className="w-48 rounded-lg bg-slate-900" aria-label="Your shared screen preview"/></div><p role="status" className={ready?'font-bold text-emerald-700':'font-bold text-amber-700'}>{status}</p>{error&&<p role="alert" className="text-rose-700">{error}</p>}</>}{host&&<><button className={btn} onClick={()=>setReview(r=>!r)}>{review?'Close':'Open'} participant monitor</button>{review&&<ProctorReview gameId={gameId}/>}</>}</section>;
}
