import React, { useCallback, useEffect, useRef, useState } from 'react';
import { useStore } from '../../store/useStore';
import { supabase } from '../../services/supabase';
import { contestRpc, getRoomState, remainingSeconds, RoomState } from '../../services/remoteContest';
import { copyTournamentLink, tournamentLink } from '../../services/roomLinks';
import { LegacyRemoteMatchRoom } from './LegacyRemoteMatchRoom';
import { ProctorPanel } from './ProctorPanel';
import { ContestWinnerBadge } from './ContestWinnerBadge';
const fiveRoundLabels=['Know the Rule','Rule Wheel','Civil Service Challenge','PSR Case Conference','Commissioner’s Final Five'];
const fiveRoundDescriptions=['Timed objective questions','Timed objective questions','Objective questions with elimination lives','Scenario-based case decisions with elimination lives','Fast jackpot finale with a final wager'];
const threeRoundLabels=['Know the Rule','The PSR Dilemma','The Civil Service Challenge'];
const button='rounded-xl bg-emerald-700 text-white px-5 py-3 font-bold disabled:opacity-40 disabled:cursor-not-allowed';

function SharedWheel({round}:{round:NonNullable<RoomState['round']>}) {
  const [spinning,setSpinning]=useState(false);
  useEffect(()=>{const id=requestAnimationFrame(()=>setSpinning(true));return()=>cancelAnimationFrame(id);},[]);
  const sections=round.sections, index=sections.indexOf(round.section_key), angle=360/sections.length;
  return <div className="text-center py-4 space-y-4"><h2 className="text-2xl font-black">Wheel of Rules</h2><p>The shared wheel selects the section for everyone.</p><div className="relative w-64 h-64 mx-auto"><span className="absolute -top-4 left-1/2 -translate-x-1/2 z-10 text-4xl text-amber-500">▼</span><div style={{background:`conic-gradient(${sections.map((_,i)=>`${['#047857','#0f766e','#b45309','#334155'][i%4]} ${i*angle}deg ${(i+1)*angle}deg`).join(',')})`,transform:`rotate(${spinning?1800-index*angle-angle/2:0}deg)`,transition:'transform 5s cubic-bezier(.12,.65,.12,1)'}} className="w-full h-full rounded-full border-8 border-amber-300 shadow-xl relative">{sections.map((s,i)=><span key={s} style={{transform:`rotate(${i*angle+angle/2}deg) translateY(-90px) rotate(90deg)`}} className="absolute left-1/2 top-1/2 -ml-5 -mt-2 text-white text-[10px] font-bold w-10">{i+1}</span>)}</div><span className="absolute inset-0 m-auto w-16 h-16 rounded-full bg-white grid place-items-center font-black text-emerald-800 shadow">PSR</span></div><details className="text-xs text-slate-500"><summary>Wheel sections</summary>{sections.map((s,i)=><p key={s}>{i+1}. {s}</p>)}</details></div>;
}
export const RemoteMatchRoom:React.FC=()=>{
 const {selectedOpponent,user,setActivePage}=useStore();const gameId=selectedOpponent?.gameId as string|undefined;
 const [room,setRoom]=useState<RoomState|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[now,setNow]=useState(0),[copied,setCopied]=useState(false);
 const [proctorReady,setProctorReady]=useState(false);
 const client=useRef(crypto.randomUUID()),alive=useRef(false),loading=useRef(false),acting=useRef(false),clock=useRef({server:0,local:0}),boundary=useRef(0);
 const refresh=useCallback(async()=>{if(!gameId||loading.current)return;loading.current=true;const sent=performance.now();try{const state=await getRoomState(gameId,client.current);if(state.game.group_competition)state.group_standings=await contestRpc<NonNullable<RoomState['group_standings']>>('contest_group_state',{p_game_id:gameId});if(state.phase==='completed'){try{state.winner_badge=await contestRpc<NonNullable<RoomState['winner_badge']>>('get_contest_winner_badge',{p_game_id:gameId});}catch{state.winner_badge=null;}}if(!alive.current)return;const received=performance.now();clock.current={server:Date.parse(state.server_now)+(received-sent)/2,local:received};setRoom(state);setNow(clock.current.server);boundary.current=state.boundary?Date.parse(state.boundary):0;}catch(e){if(alive.current)setError(e instanceof Error?e.message:'Connection lost. Reconnecting…');}finally{loading.current=false;}},[gameId]);
 useEffect(()=>{if(!gameId)return;alive.current=true;void refresh();let timeout:ReturnType<typeof setTimeout>;const queue=()=>{clearTimeout(timeout);timeout=setTimeout(()=>void refresh(),250);};const channel=supabase.channel(`contest-v2:${gameId}`).on('postgres_changes',{event:'*',schema:'public',table:'games',filter:`id=eq.${gameId}`},queue).on('postgres_changes',{event:'*',schema:'public',table:'game_players',filter:`game_id=eq.${gameId}`},queue).subscribe();const poll=setInterval(()=>void refresh(),3000),tick=setInterval(()=>{const t=clock.current.server+performance.now()-clock.current.local;setNow(t);if(boundary.current&&t>=boundary.current){boundary.current=0;void refresh();}},100);window.addEventListener('online',queue);return()=>{alive.current=false;clearTimeout(timeout);clearInterval(poll);clearInterval(tick);window.removeEventListener('online',queue);void supabase.removeChannel(channel);void contestRpc('leave_remote_room',{p_game_id:gameId,p_client_id:client.current}).catch(()=>{});};},[gameId,refresh]);
 const act=async(name:string,args:Record<string,unknown>={})=>{if(acting.current)return;acting.current=true;setBusy(true);setError('');try{await contestRpc(name,{p_game_id:gameId,...args});await refresh();}catch(e){setError(e instanceof Error?e.message:'Please retry.');}finally{acting.current=false;setBusy(false);}};
 const leave=()=>{const url=new URL(location.href);url.searchParams.delete('match');history.replaceState({},'',url);setActivePage('schedule');};
 if(!gameId)return <div className="p-8"><button onClick={leave}>Choose a tournament</button></div>;
 if(room&&!room.phase)return <LegacyRemoteMatchRoom/>;
 const host=room?.game.host_id===user?.id,connected=room?.players.filter(p=>p.connected)||[],me=room?.players.find(p=>p.user_id===user?.id),q=room?.question,phase=room?.phase;
 const existingThreeRound=room?.game.engine_version===2&&['active','completed'].includes(room.game.status);
 const roundLabels=existingThreeRound?threeRoundLabels:fiveRoundLabels;
 const seconds=room?.boundary?remainingSeconds(room.boundary,now):0;
 const eligible=!room?.game.is_proctored||proctorReady;
 const canAnswer=phase==='answer'&&!room?.answer&&!busy&&eligible;
 return <div className="max-w-7xl mx-auto px-4 py-8 space-y-5"><header className="bg-emerald-950 text-white rounded-3xl p-6 space-y-3"><div className="flex justify-between gap-4"><span className="text-emerald-200 font-bold text-sm">{room?.game.is_proctored?'PROCTORED':'OPEN'} {room?.game.competition_mode==='inter_team'?'INTER-TEAM (INNOVATORS, INVENTORS, DIFFUSERS)':room?.game.competition_mode==='inter_agency'?'NATIONAL INTER-AGENCY':'DEPARTMENT'} CONTEST {host?'· YOU ARE THE HOST':''}</span><button onClick={leave} className="underline">Leave room</button></div><h1 className="text-2xl font-black">{room?.game.title||'Connecting to tournament…'}</h1><button onClick={async()=>{try{await copyTournamentLink(gameId);setCopied(true);}catch(e){setError(String(e));}}} className="font-bold">{copied?'Link copied ✓':'Copy room link'}</button><input aria-label="Tournament invitation link" readOnly value={tournamentLink(gameId)} onFocus={e=>e.target.select()} className="block w-full bg-white/10 rounded-lg p-2 text-xs"/></header>
 {error&&<div role="alert" className="bg-rose-50 text-rose-800 border border-rose-200 p-4 rounded-xl">{error}<button className="ml-3 underline" onClick={()=>{setError('');void refresh();}}>Retry</button></div>}
 {room?.game.is_proctored&&<ProctorPanel gameId={gameId} host={host} active={phase!=='completed'&&phase!=='cancelled'} onReady={setProctorReady}/>}
 {!room?<p className="p-8">Loading shared room…</p>:<div className="grid lg:grid-cols-3 gap-6"><main className="lg:col-span-2 bg-white rounded-3xl border p-6 space-y-5">
 {phase==='lobby'?<><h2 className="text-2xl font-black">{host?'Your tournament is ready to start':'Waiting for the host'}</h2><p>Five rounds with five questions each. The shared rules wheel selects a section before every round. Accuracy and speed both count.</p><ol className="space-y-2 text-sm">{fiveRoundLabels.map((r,i)=><li key={r}><strong>Round {i+1}: {r}</strong> · {fiveRoundDescriptions[i]}</li>)}</ol><p className="text-sm text-slate-500">Scheduled: {new Date(room.game.start_datetime).toLocaleString()}. The host can start earlier with one connected guest.</p>{host?<button onClick={()=>void act('start_remote_game')} disabled={busy||connected.length<2||!eligible} className={button}>{busy?'Starting…':'Start tournament now'}</button>:<p className="font-bold text-emerald-800">Only the host can start this tournament.</p>}<p className="text-sm">The host is participant 1. {connected.length<2?'Share the link and wait for one guest to connect.':'A guest is connected. The host can start now.'}{room.game.is_proctored?' Every connected participant must complete proctor setup first.':''}</p><details className="text-sm text-slate-600"><summary>Scoring and lifelines</summary><p className="mt-2">Each round has its own 50:50 and Rulebook Peek. Rounds 3 and 4 add elimination lives. Round 5 is the jackpot finale with virtual points only. Correct answers earn points and speed bonuses; missed questions count as incorrect. Ties are decided by accuracy, then response time.</p></details></>:
 phase==='completed'?<><h2 className="text-3xl font-black text-emerald-800">Tournament complete</h2>{room.players[0]&&<div className="bg-amber-50 border border-amber-200 rounded-2xl p-5"><p className="text-xs uppercase font-black tracking-widest text-amber-800">Tournament winner</p><p className="text-2xl font-black text-slate-950">{[...room.players].sort((a,b)=>(a.rank??Number.MAX_SAFE_INTEGER)-(b.rank??Number.MAX_SAFE_INTEGER)||b.current_score-a.current_score)[0]?.full_name}</p></div>}{room.winner_badge&&<ContestWinnerBadge badge={room.winner_badge}/>}<p>Final rankings, scores and accuracy are shown alongside. Unanswered questions count as incorrect. Jackpot gains and losses are included in the score.</p></>:phase==='cancelled'?<h2>This tournament has been cancelled.</h2>:<>
 <div className="flex justify-between gap-4 font-bold"><span>Round {room.round?.round_number} · {roundLabels[(room.round?.round_number||1)-1]}</span><span role="timer" className={seconds<=5?'text-rose-600':'text-emerald-700'}>{seconds}s</span></div>
 {phase==='wheel'&&room.round?<SharedWheel key={room.round.round_number} round={room.round}/>:phase==='countdown'?<div className="py-16 text-center text-4xl font-black">Get ready… {seconds}</div>:q?<>
 <p className="text-sm font-semibold text-emerald-700">{room.round?.section_key} · Question {q.question_order%5+1}/5</p>
 {([3,4].includes(q.round_number)||existingThreeRound&&q.round_number===3)&&<div className="space-y-3"><div className="bg-amber-50 border border-amber-200 p-4 rounded-xl flex flex-wrap gap-4 font-bold"><span>Lives remaining: {me?.life_tokens??0}</span>{existingThreeRound&&q.round_number===3&&<span>Jackpot: {me?.jackpot_balance} points</span>}<span>Reward +{q.base_points} · Risk −{q.life_cost} {q.life_cost===1?'life':'lives'}</span></div>{(me?.life_tokens??0)<=0&&<div className="bg-rose-950 text-white p-4 rounded-2xl border-2 border-rose-500 shadow-xl space-y-1 animate-fadeIn"><div className="flex items-center gap-2 font-black text-rose-300 text-sm"><span>🚫</span> SPECTATOR MODE ACTIVATED — ELIMINATED FROM THIS ROUND</div><p className="text-xs text-rose-100">You have used all your Life Tokens for this elimination round. Your answer options are locked so you can observe the remaining contestants. You will automatically rejoin active play in <strong>Round 5 (The Jackpot Finale)</strong>!</p></div>}</div>}
 {q.round_number===5&&<div className="bg-amber-50 border border-amber-200 p-4 rounded-xl flex flex-wrap gap-4 font-bold"><span>Finale jackpot: {me?.jackpot_balance} points</span><span>Reward +{q.base_points}</span></div>}
 <h2 className="text-xl font-bold leading-relaxed">{q.question_text}</h2>
 {phase==='wager'?<div className="space-y-3"><p>Lock your virtual points wager before answering. No wager defaults to 0.</p><div className="flex flex-wrap gap-2">{[0,10,25,50,100].map(n=><button key={n} className={button} disabled={busy||!eligible||seconds===0||room.wager!==null||n>(me?.jackpot_balance??0)||(me?.life_tokens??0)<=0} onClick={()=>void act('place_contest_wager',{p_question_id:q.id,p_amount:n})}>{n===0?'Play safe · 0':n}</button>)}</div>{room.wager!==null&&<p>Wager locked: {room.wager} points.</p>}</div>:<>
 <div className="grid gap-3">{q.options.map((option,i)=>{
    const isEliminated = ([3,4].includes(q.round_number)||existingThreeRound&&q.round_number===3)&&(me?.life_tokens??0)<=0;
    return <button key={i} disabled={!canAnswer||isEliminated||!!room.lifelines.hidden_options?.includes(i)} onClick={()=>void act('submit_player_answer',{p_question_id:q.id,p_selected_option:i,p_response_time_ms:0})} className={`p-4 rounded-xl border-2 text-left ${q.correct_option_index===i?'border-emerald-600 bg-emerald-50':room.answer?.selected_option===i?'border-rose-500 bg-rose-50':'border-slate-200'} disabled:cursor-default disabled:opacity-60`}>{String.fromCharCode(65+i)}. {room.lifelines.hidden_options?.includes(i)?'Removed by 50:50':option}</button>;
  })}</div>
 <div className="flex flex-wrap gap-3"><button className={button} disabled={!canAnswer||room.lifelines.used_fifty} onClick={()=>void act('use_contest_lifeline',{p_question_id:q.id,p_kind:'fifty'})}>50:50 {room.lifelines.used_fifty?'· Used':''}</button><button className={button} disabled={!canAnswer||room.lifelines.used_peek} onClick={()=>void act('use_contest_lifeline',{p_question_id:q.id,p_kind:'peek'})}>Rulebook Peek {room.lifelines.used_peek?'· Used':''}</button></div>
 {room.lifelines.peek&&<p className="bg-blue-50 p-4 rounded-xl">{room.lifelines.peek}</p>}
 {room.answer&&<p role="status" className="font-bold">{room.answer.selected_option<0?'Time expired':room.answer.is_correct?'Correct decision':'Incorrect decision'} · {room.answer.points_earned>0?'+':''}{room.answer.points_earned} points{room.answer.lives_lost?` · −${room.answer.lives_lost} life`:''}</p>}
 {q.explanation&&<div className="bg-emerald-50 p-4 rounded-xl space-y-2"><h3 className="font-black">THE PSR RULE BEHIND THE DECISION</h3><strong>{q.rule_ref}</strong><p>{q.explanation}</p><p className="text-xs text-slate-500">Source: {q.source_ref}</p></div>}
 <p className="text-xs text-slate-500">{busy?'Saving…':room.answer||phase==='reveal'?'The next question opens automatically for everyone.':'Choose before the timer ends. The server controls the deadline.'}</p></>}
 </>:<p>Synchronizing the next stage…</p>}</>}
 </main><aside className="bg-white border rounded-3xl p-5 space-y-4">{!!room.group_standings?.length&&<section className="space-y-3"><h2 className="font-black">Group standings</h2>{room.group_standings.map(group=><div key={group.group_name} className="border rounded-xl p-3"><div className="flex justify-between gap-2 font-bold"><span>#{group.group_rank} {group.group_name}{group.winner?' · Winner':''}</span><span>{group.total_score} pts</span></div><p className="text-xs text-slate-500">{group.correct_answers} correct answers</p><ul className="mt-2 space-y-1 text-xs">{group.members.map(member=><li key={member.user_id} className="flex justify-between gap-2"><span>{member.full_name}</span><span>{member.score} pts</span></li>)}</ul></div>)}</section>}{!!room.round_awards?.length&&<section className="space-y-2"><h2 className="font-black">Fastest Finger · Round Awards</h2>{room.round_awards.map(award=><div key={award.round_number} className="border-l-4 border-amber-400 bg-amber-50 px-3 py-2 text-sm"><p className="font-bold">Round {award.round_number}: {award.full_name}</p><p className="text-xs text-slate-600">{award.correct_answers} correct · {Math.round(award.response_time_ms/1000)}s response time</p></div>)}</section>}<h2 className="font-black">Connected Room Participants ({connected.length})</h2><p className="text-xs text-slate-500">{room.players.length} registered / {room.game.max_players} capacity. Updates automatically; inactive connections expire within 25 seconds.</p><ul className="space-y-3 max-h-[40rem] overflow-y-auto">{room.players.map(p=><li key={p.user_id} className="border-b pb-3 text-sm"><div className="flex justify-between gap-2"><strong>{p.rank?`#${p.rank} `:''}{p.full_name}{p.user_id===room.game.host_id?' (Host)':''}{p.user_id===user?.id?' (You)':''}</strong><strong>{p.current_score}</strong></div><p className="text-xs text-slate-500">{p.department} · {p.connected?'Connected':'Offline'}</p>{phase==='completed'&&<p>Accuracy: {p.total_accuracy??0}%</p>}</li>)}</ul></aside></div>}</div>;
};
